// This file is auto-generated by @hey-api/openapi-ts

export const AnnotationStatusSchema = {
    type: 'string',
    enum: ['none', 'linked', 'conflict', 'error'],
    title: 'AnnotationStatus',
    description: 'Annotation status enum.'
} as const;

export const BatchTagRequestSchema = {
    properties: {
        sample_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Sample Ids'
        },
        tag_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Tag Ids'
        }
    },
    type: 'object',
    required: ['sample_ids', 'tag_ids'],
    title: 'BatchTagRequest',
    description: 'Request for batch tagging samples.'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_samples_import_samplesSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        minio_instance_id: {
            type: 'string',
            format: 'uuid',
            title: 'Minio Instance Id'
        },
        bucket: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bucket'
        },
        validate_files: {
            type: 'boolean',
            title: 'Validate Files',
            default: true
        }
    },
    type: 'object',
    required: ['file', 'minio_instance_id'],
    title: 'Body_samples-import_samples'
} as const;

export const Body_samples_preview_import_csvSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_samples-preview_import_csv'
} as const;

export const CSVPreviewResponseSchema = {
    properties: {
        total_rows: {
            type: 'integer',
            title: 'Total Rows'
        },
        columns: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Columns'
        },
        sample_rows: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Sample Rows'
        },
        has_tags_column: {
            type: 'boolean',
            title: 'Has Tags Column'
        },
        image_count: {
            type: 'integer',
            title: 'Image Count'
        },
        annotation_count: {
            type: 'integer',
            title: 'Annotation Count'
        }
    },
    type: 'object',
    required: ['total_rows', 'columns', 'sample_rows', 'has_tags_column', 'image_count', 'annotation_count'],
    title: 'CSVPreviewResponse',
    description: 'CSV preview response for API.'
} as const;

export const DailyStatsSchema = {
    properties: {
        date: {
            type: 'string',
            title: 'Date'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['date', 'count'],
    title: 'DailyStats',
    description: 'Daily statistics.'
} as const;

export const DashboardOverviewSchema = {
    properties: {
        total_samples: {
            type: 'integer',
            title: 'Total Samples'
        },
        total_datasets: {
            type: 'integer',
            title: 'Total Datasets'
        },
        total_tags: {
            type: 'integer',
            title: 'Total Tags'
        },
        total_minio_instances: {
            type: 'integer',
            title: 'Total Minio Instances'
        },
        samples_today: {
            type: 'integer',
            title: 'Samples Today'
        },
        samples_this_week: {
            type: 'integer',
            title: 'Samples This Week'
        }
    },
    type: 'object',
    required: ['total_samples', 'total_datasets', 'total_tags', 'total_minio_instances', 'samples_today', 'samples_this_week'],
    title: 'DashboardOverview',
    description: 'Dashboard overview statistics.'
} as const;

export const DatasetAddSamplesRequestSchema = {
    properties: {
        filters: {
            '$ref': '#/components/schemas/FilterParams'
        },
        sampling: {
            '$ref': '#/components/schemas/SamplingConfig'
        }
    },
    type: 'object',
    required: ['filters', 'sampling'],
    title: 'DatasetAddSamplesRequest',
    description: 'Request for adding samples to existing dataset.'
} as const;

export const DatasetBuildRequestSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        filters: {
            '$ref': '#/components/schemas/FilterParams'
        },
        sampling: {
            '$ref': '#/components/schemas/SamplingConfig'
        }
    },
    type: 'object',
    required: ['name', 'filters', 'sampling'],
    title: 'DatasetBuildRequest',
    description: 'Request for building a new dataset.'
} as const;

export const DatasetCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_public: {
            type: 'boolean',
            title: 'Is Public',
            default: false
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DatasetCreate',
    description: 'Properties to receive on dataset creation.'
} as const;

export const DatasetPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_public: {
            type: 'boolean',
            title: 'Is Public',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        sample_count: {
            type: 'integer',
            title: 'Sample Count'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id', 'sample_count', 'created_at', 'updated_at'],
    title: 'DatasetPublic',
    description: 'Properties to return via API.'
} as const;

export const DatasetSamplesRequestSchema = {
    properties: {
        sample_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Sample Ids'
        }
    },
    type: 'object',
    required: ['sample_ids'],
    title: 'DatasetSamplesRequest',
    description: 'Request for adding/removing samples from dataset.'
} as const;

export const DatasetUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_public: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Public'
        }
    },
    type: 'object',
    title: 'DatasetUpdate',
    description: 'Properties to receive on dataset update.'
} as const;

export const DatasetsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DatasetPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DatasetsPublic',
    description: 'Paginated datasets response.'
} as const;

export const FilterParamsSchema = {
    properties: {
        tags_include: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags Include'
        },
        tags_exclude: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags Exclude'
        },
        minio_instance_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Minio Instance Id'
        },
        bucket: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bucket'
        },
        prefix: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prefix'
        },
        date_from: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date From'
        },
        date_to: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date To'
        },
        annotation_classes: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Annotation Classes'
        },
        object_count_min: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Object Count Min'
        },
        object_count_max: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Object Count Max'
        },
        annotation_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AnnotationStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'FilterParams',
    description: 'Parameters for filtering samples.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImportTaskPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            '$ref': '#/components/schemas/ImportTaskStatus'
        },
        total_rows: {
            type: 'integer',
            title: 'Total Rows'
        },
        progress: {
            type: 'integer',
            title: 'Progress'
        },
        created: {
            type: 'integer',
            title: 'Created'
        },
        skipped: {
            type: 'integer',
            title: 'Skipped'
        },
        errors: {
            type: 'integer',
            title: 'Errors'
        },
        annotations_linked: {
            type: 'integer',
            title: 'Annotations Linked'
        },
        tags_created: {
            type: 'integer',
            title: 'Tags Created'
        },
        error_details: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Details'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: ['id', 'status', 'total_rows', 'progress', 'created', 'skipped', 'errors', 'annotations_linked', 'tags_created', 'error_details', 'created_at', 'updated_at', 'completed_at'],
    title: 'ImportTaskPublic',
    description: 'Import task response for API.'
} as const;

export const ImportTaskStatusSchema = {
    type: 'string',
    enum: ['pending', 'running', 'completed', 'failed'],
    title: 'ImportTaskStatus',
    description: 'Import task status enum.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MinIOInstanceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        endpoint: {
            type: 'string',
            maxLength: 512,
            title: 'Endpoint'
        },
        secure: {
            type: 'boolean',
            title: 'Secure',
            default: true
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        access_key: {
            type: 'string',
            maxLength: 255,
            title: 'Access Key'
        },
        secret_key: {
            type: 'string',
            maxLength: 255,
            title: 'Secret Key'
        }
    },
    type: 'object',
    required: ['name', 'endpoint', 'access_key', 'secret_key'],
    title: 'MinIOInstanceCreate',
    description: 'Properties to receive on MinIO instance creation.'
} as const;

export const MinIOInstancePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        endpoint: {
            type: 'string',
            maxLength: 512,
            title: 'Endpoint'
        },
        secure: {
            type: 'boolean',
            title: 'Secure',
            default: true
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'endpoint', 'id', 'owner_id', 'created_at', 'updated_at'],
    title: 'MinIOInstancePublic',
    description: 'Properties to return via API.'
} as const;

export const MinIOInstanceUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        endpoint: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Endpoint'
        },
        secure: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secure'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        access_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Access Key'
        },
        secret_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret Key'
        }
    },
    type: 'object',
    title: 'MinIOInstanceUpdate',
    description: 'Properties to receive on MinIO instance update.'
} as const;

export const MinIOInstancesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MinIOInstancePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MinIOInstancesPublic',
    description: 'Paginated MinIO instances response.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SampleHistoryActionSchema = {
    type: 'string',
    enum: ['created', 'updated', 'deleted', 'tagged', 'untagged', 'added_to_dataset', 'removed_from_dataset', 'annotation_linked', 'annotation_conflict', 'annotation_removed'],
    title: 'SampleHistoryAction',
    description: 'Sample history action enum.'
} as const;

export const SampleHistoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sample_id: {
            type: 'string',
            format: 'uuid',
            title: 'Sample Id'
        },
        action: {
            '$ref': '#/components/schemas/SampleHistoryAction'
        },
        details: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Details'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'sample_id', 'action', 'details', 'created_at'],
    title: 'SampleHistoryPublic',
    description: 'Properties to return via API.'
} as const;

export const SamplePreviewAnnotationSchema = {
    properties: {
        objects: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Objects'
        },
        class_counts: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Class Counts'
        },
        image_width: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Width'
        },
        image_height: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Height'
        }
    },
    type: 'object',
    title: 'SamplePreviewAnnotation',
    description: 'Annotation data for sample preview.'
} as const;

export const SamplePreviewResponseSchema = {
    properties: {
        presigned_url: {
            type: 'string',
            title: 'Presigned Url'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        },
        annotation: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SamplePreviewAnnotation'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        sample: {
            '$ref': '#/components/schemas/SamplePublic'
        }
    },
    type: 'object',
    required: ['presigned_url', 'expires_in', 'sample'],
    title: 'SamplePreviewResponse',
    description: 'Response for sample preview API.'
} as const;

export const SamplePublicSchema = {
    properties: {
        object_key: {
            type: 'string',
            maxLength: 1024,
            title: 'Object Key'
        },
        bucket: {
            type: 'string',
            maxLength: 255,
            title: 'Bucket'
        },
        file_name: {
            type: 'string',
            maxLength: 255,
            title: 'File Name'
        },
        file_size: {
            type: 'integer',
            title: 'File Size',
            default: 0
        },
        content_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        },
        etag: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Etag'
        },
        extra_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra Data'
        },
        file_hash: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Hash'
        },
        file_stem: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Stem'
        },
        annotation_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Annotation Key'
        },
        annotation_hash: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Annotation Hash'
        },
        annotation_status: {
            '$ref': '#/components/schemas/AnnotationStatus',
            default: 'none'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        minio_instance_id: {
            type: 'string',
            format: 'uuid',
            title: 'Minio Instance Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        status: {
            '$ref': '#/components/schemas/SampleStatus'
        },
        source: {
            '$ref': '#/components/schemas/SampleSource'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['object_key', 'bucket', 'file_name', 'id', 'minio_instance_id', 'owner_id', 'status', 'source', 'created_at', 'updated_at'],
    title: 'SamplePublic',
    description: 'Properties to return via API.'
} as const;

export const SampleSourceSchema = {
    type: 'string',
    enum: ['webhook', 'sync', 'import', 'manual'],
    title: 'SampleSource',
    description: 'Sample source enum.'
} as const;

export const SampleStatusSchema = {
    type: 'string',
    enum: ['active', 'deleted', 'archived'],
    title: 'SampleStatus',
    description: 'Sample status enum.'
} as const;

export const SampleWithTagsSchema = {
    properties: {
        object_key: {
            type: 'string',
            maxLength: 1024,
            title: 'Object Key'
        },
        bucket: {
            type: 'string',
            maxLength: 255,
            title: 'Bucket'
        },
        file_name: {
            type: 'string',
            maxLength: 255,
            title: 'File Name'
        },
        file_size: {
            type: 'integer',
            title: 'File Size',
            default: 0
        },
        content_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        },
        etag: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Etag'
        },
        extra_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra Data'
        },
        file_hash: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Hash'
        },
        file_stem: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Stem'
        },
        annotation_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Annotation Key'
        },
        annotation_hash: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Annotation Hash'
        },
        annotation_status: {
            '$ref': '#/components/schemas/AnnotationStatus',
            default: 'none'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        minio_instance_id: {
            type: 'string',
            format: 'uuid',
            title: 'Minio Instance Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        status: {
            '$ref': '#/components/schemas/SampleStatus'
        },
        source: {
            '$ref': '#/components/schemas/SampleSource'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Tags',
            default: []
        }
    },
    type: 'object',
    required: ['object_key', 'bucket', 'file_name', 'id', 'minio_instance_id', 'owner_id', 'status', 'source', 'created_at', 'updated_at'],
    title: 'SampleWithTags',
    description: 'Sample with tags for detailed view.'
} as const;

export const SamplesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SamplePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SamplesPublic',
    description: 'Paginated samples response.'
} as const;

export const SamplingConfigSchema = {
    properties: {
        mode: {
            '$ref': '#/components/schemas/SamplingMode',
            default: 'all'
        },
        count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count'
        },
        class_targets: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Class Targets'
        },
        seed: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seed'
        }
    },
    type: 'object',
    title: 'SamplingConfig',
    description: 'Configuration for sampling strategy.'
} as const;

export const SamplingModeSchema = {
    type: 'string',
    enum: ['all', 'random', 'class_targets'],
    title: 'SamplingMode',
    description: 'Sampling mode for dataset building.'
} as const;

export const TagCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 7
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'TagCreate',
    description: 'Properties to receive on tag creation.'
} as const;

export const TagDistributionSchema = {
    properties: {
        tag_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tag Id'
        },
        tag_name: {
            type: 'string',
            title: 'Tag Name'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['tag_id', 'tag_name', 'count'],
    title: 'TagDistribution',
    description: 'Tag distribution statistics.'
} as const;

export const TagPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 7
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'parent_id', 'owner_id', 'created_at', 'updated_at'],
    title: 'TagPublic',
    description: 'Properties to return via API.'
} as const;

export const TagUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 7
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    title: 'TagUpdate',
    description: 'Properties to receive on tag update.'
} as const;

export const TagWithChildrenSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 7
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        children: {
            items: {
                '$ref': '#/components/schemas/TagWithChildren'
            },
            type: 'array',
            title: 'Children',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'id', 'parent_id', 'owner_id', 'created_at', 'updated_at'],
    title: 'TagWithChildren',
    description: 'Tag with children for tree structure.'
} as const;

export const TagsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TagsPublic',
    description: 'Paginated tags response.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WatchedPathCreateSchema = {
    properties: {
        bucket: {
            type: 'string',
            maxLength: 255,
            title: 'Bucket'
        },
        prefix: {
            type: 'string',
            maxLength: 1024,
            title: 'Prefix',
            default: ''
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        minio_instance_id: {
            type: 'string',
            format: 'uuid',
            title: 'Minio Instance Id'
        }
    },
    type: 'object',
    required: ['bucket', 'minio_instance_id'],
    title: 'WatchedPathCreate',
    description: 'Properties to receive on watched path creation.'
} as const;

export const WatchedPathPublicSchema = {
    properties: {
        bucket: {
            type: 'string',
            maxLength: 255,
            title: 'Bucket'
        },
        prefix: {
            type: 'string',
            maxLength: 1024,
            title: 'Prefix',
            default: ''
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        minio_instance_id: {
            type: 'string',
            format: 'uuid',
            title: 'Minio Instance Id'
        },
        last_sync_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Sync At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['bucket', 'id', 'minio_instance_id', 'last_sync_at', 'created_at', 'updated_at'],
    title: 'WatchedPathPublic',
    description: 'Properties to return via API.'
} as const;

export const WatchedPathUpdateSchema = {
    properties: {
        bucket: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bucket'
        },
        prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prefix'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'WatchedPathUpdate',
    description: 'Properties to receive on watched path update.'
} as const;

export const WatchedPathsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WatchedPathPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WatchedPathsPublic',
    description: 'Paginated watched paths response.'
} as const;