/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTagsRouteImport } from './routes/_layout/tags'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOpsRouteImport } from './routes/_layout/ops'
import { Route as LayoutMinioInstancesRouteImport } from './routes/_layout/minio-instances'
import { Route as LayoutImportRouteImport } from './routes/_layout/import'
import { Route as LayoutDatasetsRouteImport } from './routes/_layout/datasets'
import { Route as LayoutBuildRouteImport } from './routes/_layout/build'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutSamplesIndexRouteImport } from './routes/_layout/samples/index'
import { Route as LayoutDatasetsIndexRouteImport } from './routes/_layout/datasets/index'
import { Route as LayoutSettingsWatchedPathsRouteImport } from './routes/_layout/settings/watched-paths'
import { Route as LayoutSettingsUsersRouteImport } from './routes/_layout/settings/users'
import { Route as LayoutSettingsTagsRouteImport } from './routes/_layout/settings/tags'
import { Route as LayoutSettingsMinioRouteImport } from './routes/_layout/settings/minio'
import { Route as LayoutSamplesSampleIdRouteImport } from './routes/_layout/samples/$sampleId'
import { Route as LayoutDatasetsBuildRouteImport } from './routes/_layout/datasets/build'
import { Route as LayoutSettingsTaggingRulesIndexRouteImport } from './routes/_layout/settings/tagging-rules/index'
import { Route as LayoutDatasetsDatasetIdIndexRouteImport } from './routes/_layout/datasets/$datasetId/index'
import { Route as LayoutSettingsTaggingRulesNewRouteImport } from './routes/_layout/settings/tagging-rules/new'
import { Route as LayoutDatasetsDatasetIdReviewRouteImport } from './routes/_layout/datasets/$datasetId/review'
import { Route as LayoutDatasetsDatasetIdAddSamplesRouteImport } from './routes/_layout/datasets/$datasetId.add-samples'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTagsRoute = LayoutTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOpsRoute = LayoutOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMinioInstancesRoute = LayoutMinioInstancesRouteImport.update({
  id: '/minio-instances',
  path: '/minio-instances',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImportRoute = LayoutImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDatasetsRoute = LayoutDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuildRoute = LayoutBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSamplesIndexRoute = LayoutSamplesIndexRouteImport.update({
  id: '/samples/',
  path: '/samples/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDatasetsIndexRoute = LayoutDatasetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutDatasetsRoute,
} as any)
const LayoutSettingsWatchedPathsRoute =
  LayoutSettingsWatchedPathsRouteImport.update({
    id: '/watched-paths',
    path: '/watched-paths',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsUsersRoute = LayoutSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsTagsRoute = LayoutSettingsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsMinioRoute = LayoutSettingsMinioRouteImport.update({
  id: '/minio',
  path: '/minio',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSamplesSampleIdRoute = LayoutSamplesSampleIdRouteImport.update({
  id: '/samples/$sampleId',
  path: '/samples/$sampleId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDatasetsBuildRoute = LayoutDatasetsBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => LayoutDatasetsRoute,
} as any)
const LayoutSettingsTaggingRulesIndexRoute =
  LayoutSettingsTaggingRulesIndexRouteImport.update({
    id: '/tagging-rules/',
    path: '/tagging-rules/',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutDatasetsDatasetIdIndexRoute =
  LayoutDatasetsDatasetIdIndexRouteImport.update({
    id: '/$datasetId/',
    path: '/$datasetId/',
    getParentRoute: () => LayoutDatasetsRoute,
  } as any)
const LayoutSettingsTaggingRulesNewRoute =
  LayoutSettingsTaggingRulesNewRouteImport.update({
    id: '/tagging-rules/new',
    path: '/tagging-rules/new',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutDatasetsDatasetIdReviewRoute =
  LayoutDatasetsDatasetIdReviewRouteImport.update({
    id: '/$datasetId/review',
    path: '/$datasetId/review',
    getParentRoute: () => LayoutDatasetsRoute,
  } as any)
const LayoutDatasetsDatasetIdAddSamplesRoute =
  LayoutDatasetsDatasetIdAddSamplesRouteImport.update({
    id: '/$datasetId/add-samples',
    path: '/$datasetId/add-samples',
    getParentRoute: () => LayoutDatasetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/build': typeof LayoutBuildRoute
  '/datasets': typeof LayoutDatasetsRouteWithChildren
  '/import': typeof LayoutImportRoute
  '/minio-instances': typeof LayoutMinioInstancesRoute
  '/ops': typeof LayoutOpsRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/tags': typeof LayoutTagsRoute
  '/': typeof LayoutIndexRoute
  '/datasets/build': typeof LayoutDatasetsBuildRoute
  '/samples/$sampleId': typeof LayoutSamplesSampleIdRoute
  '/settings/minio': typeof LayoutSettingsMinioRoute
  '/settings/tags': typeof LayoutSettingsTagsRoute
  '/settings/users': typeof LayoutSettingsUsersRoute
  '/settings/watched-paths': typeof LayoutSettingsWatchedPathsRoute
  '/datasets/': typeof LayoutDatasetsIndexRoute
  '/samples': typeof LayoutSamplesIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/datasets/$datasetId/add-samples': typeof LayoutDatasetsDatasetIdAddSamplesRoute
  '/datasets/$datasetId/review': typeof LayoutDatasetsDatasetIdReviewRoute
  '/settings/tagging-rules/new': typeof LayoutSettingsTaggingRulesNewRoute
  '/datasets/$datasetId': typeof LayoutDatasetsDatasetIdIndexRoute
  '/settings/tagging-rules': typeof LayoutSettingsTaggingRulesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/build': typeof LayoutBuildRoute
  '/import': typeof LayoutImportRoute
  '/minio-instances': typeof LayoutMinioInstancesRoute
  '/ops': typeof LayoutOpsRoute
  '/tags': typeof LayoutTagsRoute
  '/': typeof LayoutIndexRoute
  '/datasets/build': typeof LayoutDatasetsBuildRoute
  '/samples/$sampleId': typeof LayoutSamplesSampleIdRoute
  '/settings/minio': typeof LayoutSettingsMinioRoute
  '/settings/tags': typeof LayoutSettingsTagsRoute
  '/settings/users': typeof LayoutSettingsUsersRoute
  '/settings/watched-paths': typeof LayoutSettingsWatchedPathsRoute
  '/datasets': typeof LayoutDatasetsIndexRoute
  '/samples': typeof LayoutSamplesIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/datasets/$datasetId/add-samples': typeof LayoutDatasetsDatasetIdAddSamplesRoute
  '/datasets/$datasetId/review': typeof LayoutDatasetsDatasetIdReviewRoute
  '/settings/tagging-rules/new': typeof LayoutSettingsTaggingRulesNewRoute
  '/datasets/$datasetId': typeof LayoutDatasetsDatasetIdIndexRoute
  '/settings/tagging-rules': typeof LayoutSettingsTaggingRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/build': typeof LayoutBuildRoute
  '/_layout/datasets': typeof LayoutDatasetsRouteWithChildren
  '/_layout/import': typeof LayoutImportRoute
  '/_layout/minio-instances': typeof LayoutMinioInstancesRoute
  '/_layout/ops': typeof LayoutOpsRoute
  '/_layout/settings': typeof LayoutSettingsRouteWithChildren
  '/_layout/tags': typeof LayoutTagsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/datasets/build': typeof LayoutDatasetsBuildRoute
  '/_layout/samples/$sampleId': typeof LayoutSamplesSampleIdRoute
  '/_layout/settings/minio': typeof LayoutSettingsMinioRoute
  '/_layout/settings/tags': typeof LayoutSettingsTagsRoute
  '/_layout/settings/users': typeof LayoutSettingsUsersRoute
  '/_layout/settings/watched-paths': typeof LayoutSettingsWatchedPathsRoute
  '/_layout/datasets/': typeof LayoutDatasetsIndexRoute
  '/_layout/samples/': typeof LayoutSamplesIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/datasets/$datasetId/add-samples': typeof LayoutDatasetsDatasetIdAddSamplesRoute
  '/_layout/datasets/$datasetId/review': typeof LayoutDatasetsDatasetIdReviewRoute
  '/_layout/settings/tagging-rules/new': typeof LayoutSettingsTaggingRulesNewRoute
  '/_layout/datasets/$datasetId/': typeof LayoutDatasetsDatasetIdIndexRoute
  '/_layout/settings/tagging-rules/': typeof LayoutSettingsTaggingRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/build'
    | '/datasets'
    | '/import'
    | '/minio-instances'
    | '/ops'
    | '/settings'
    | '/tags'
    | '/'
    | '/datasets/build'
    | '/samples/$sampleId'
    | '/settings/minio'
    | '/settings/tags'
    | '/settings/users'
    | '/settings/watched-paths'
    | '/datasets/'
    | '/samples'
    | '/settings/'
    | '/datasets/$datasetId/add-samples'
    | '/datasets/$datasetId/review'
    | '/settings/tagging-rules/new'
    | '/datasets/$datasetId'
    | '/settings/tagging-rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/build'
    | '/import'
    | '/minio-instances'
    | '/ops'
    | '/tags'
    | '/'
    | '/datasets/build'
    | '/samples/$sampleId'
    | '/settings/minio'
    | '/settings/tags'
    | '/settings/users'
    | '/settings/watched-paths'
    | '/datasets'
    | '/samples'
    | '/settings'
    | '/datasets/$datasetId/add-samples'
    | '/datasets/$datasetId/review'
    | '/settings/tagging-rules/new'
    | '/datasets/$datasetId'
    | '/settings/tagging-rules'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/build'
    | '/_layout/datasets'
    | '/_layout/import'
    | '/_layout/minio-instances'
    | '/_layout/ops'
    | '/_layout/settings'
    | '/_layout/tags'
    | '/_layout/'
    | '/_layout/datasets/build'
    | '/_layout/samples/$sampleId'
    | '/_layout/settings/minio'
    | '/_layout/settings/tags'
    | '/_layout/settings/users'
    | '/_layout/settings/watched-paths'
    | '/_layout/datasets/'
    | '/_layout/samples/'
    | '/_layout/settings/'
    | '/_layout/datasets/$datasetId/add-samples'
    | '/_layout/datasets/$datasetId/review'
    | '/_layout/settings/tagging-rules/new'
    | '/_layout/datasets/$datasetId/'
    | '/_layout/settings/tagging-rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tags': {
      id: '/_layout/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof LayoutTagsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ops': {
      id: '/_layout/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof LayoutOpsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/minio-instances': {
      id: '/_layout/minio-instances'
      path: '/minio-instances'
      fullPath: '/minio-instances'
      preLoaderRoute: typeof LayoutMinioInstancesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/import': {
      id: '/_layout/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof LayoutImportRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/datasets': {
      id: '/_layout/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof LayoutDatasetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/build': {
      id: '/_layout/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof LayoutBuildRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/samples/': {
      id: '/_layout/samples/'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof LayoutSamplesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/datasets/': {
      id: '/_layout/datasets/'
      path: '/'
      fullPath: '/datasets/'
      preLoaderRoute: typeof LayoutDatasetsIndexRouteImport
      parentRoute: typeof LayoutDatasetsRoute
    }
    '/_layout/settings/watched-paths': {
      id: '/_layout/settings/watched-paths'
      path: '/watched-paths'
      fullPath: '/settings/watched-paths'
      preLoaderRoute: typeof LayoutSettingsWatchedPathsRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/users': {
      id: '/_layout/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof LayoutSettingsUsersRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/tags': {
      id: '/_layout/settings/tags'
      path: '/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof LayoutSettingsTagsRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/minio': {
      id: '/_layout/settings/minio'
      path: '/minio'
      fullPath: '/settings/minio'
      preLoaderRoute: typeof LayoutSettingsMinioRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/samples/$sampleId': {
      id: '/_layout/samples/$sampleId'
      path: '/samples/$sampleId'
      fullPath: '/samples/$sampleId'
      preLoaderRoute: typeof LayoutSamplesSampleIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/datasets/build': {
      id: '/_layout/datasets/build'
      path: '/build'
      fullPath: '/datasets/build'
      preLoaderRoute: typeof LayoutDatasetsBuildRouteImport
      parentRoute: typeof LayoutDatasetsRoute
    }
    '/_layout/settings/tagging-rules/': {
      id: '/_layout/settings/tagging-rules/'
      path: '/tagging-rules'
      fullPath: '/settings/tagging-rules'
      preLoaderRoute: typeof LayoutSettingsTaggingRulesIndexRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/datasets/$datasetId/': {
      id: '/_layout/datasets/$datasetId/'
      path: '/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof LayoutDatasetsDatasetIdIndexRouteImport
      parentRoute: typeof LayoutDatasetsRoute
    }
    '/_layout/settings/tagging-rules/new': {
      id: '/_layout/settings/tagging-rules/new'
      path: '/tagging-rules/new'
      fullPath: '/settings/tagging-rules/new'
      preLoaderRoute: typeof LayoutSettingsTaggingRulesNewRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/datasets/$datasetId/review': {
      id: '/_layout/datasets/$datasetId/review'
      path: '/$datasetId/review'
      fullPath: '/datasets/$datasetId/review'
      preLoaderRoute: typeof LayoutDatasetsDatasetIdReviewRouteImport
      parentRoute: typeof LayoutDatasetsRoute
    }
    '/_layout/datasets/$datasetId/add-samples': {
      id: '/_layout/datasets/$datasetId/add-samples'
      path: '/$datasetId/add-samples'
      fullPath: '/datasets/$datasetId/add-samples'
      preLoaderRoute: typeof LayoutDatasetsDatasetIdAddSamplesRouteImport
      parentRoute: typeof LayoutDatasetsRoute
    }
  }
}

interface LayoutDatasetsRouteChildren {
  LayoutDatasetsBuildRoute: typeof LayoutDatasetsBuildRoute
  LayoutDatasetsIndexRoute: typeof LayoutDatasetsIndexRoute
  LayoutDatasetsDatasetIdAddSamplesRoute: typeof LayoutDatasetsDatasetIdAddSamplesRoute
  LayoutDatasetsDatasetIdReviewRoute: typeof LayoutDatasetsDatasetIdReviewRoute
  LayoutDatasetsDatasetIdIndexRoute: typeof LayoutDatasetsDatasetIdIndexRoute
}

const LayoutDatasetsRouteChildren: LayoutDatasetsRouteChildren = {
  LayoutDatasetsBuildRoute: LayoutDatasetsBuildRoute,
  LayoutDatasetsIndexRoute: LayoutDatasetsIndexRoute,
  LayoutDatasetsDatasetIdAddSamplesRoute:
    LayoutDatasetsDatasetIdAddSamplesRoute,
  LayoutDatasetsDatasetIdReviewRoute: LayoutDatasetsDatasetIdReviewRoute,
  LayoutDatasetsDatasetIdIndexRoute: LayoutDatasetsDatasetIdIndexRoute,
}

const LayoutDatasetsRouteWithChildren = LayoutDatasetsRoute._addFileChildren(
  LayoutDatasetsRouteChildren,
)

interface LayoutSettingsRouteChildren {
  LayoutSettingsMinioRoute: typeof LayoutSettingsMinioRoute
  LayoutSettingsTagsRoute: typeof LayoutSettingsTagsRoute
  LayoutSettingsUsersRoute: typeof LayoutSettingsUsersRoute
  LayoutSettingsWatchedPathsRoute: typeof LayoutSettingsWatchedPathsRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutSettingsTaggingRulesNewRoute: typeof LayoutSettingsTaggingRulesNewRoute
  LayoutSettingsTaggingRulesIndexRoute: typeof LayoutSettingsTaggingRulesIndexRoute
}

const LayoutSettingsRouteChildren: LayoutSettingsRouteChildren = {
  LayoutSettingsMinioRoute: LayoutSettingsMinioRoute,
  LayoutSettingsTagsRoute: LayoutSettingsTagsRoute,
  LayoutSettingsUsersRoute: LayoutSettingsUsersRoute,
  LayoutSettingsWatchedPathsRoute: LayoutSettingsWatchedPathsRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutSettingsTaggingRulesNewRoute: LayoutSettingsTaggingRulesNewRoute,
  LayoutSettingsTaggingRulesIndexRoute: LayoutSettingsTaggingRulesIndexRoute,
}

const LayoutSettingsRouteWithChildren = LayoutSettingsRoute._addFileChildren(
  LayoutSettingsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBuildRoute: typeof LayoutBuildRoute
  LayoutDatasetsRoute: typeof LayoutDatasetsRouteWithChildren
  LayoutImportRoute: typeof LayoutImportRoute
  LayoutMinioInstancesRoute: typeof LayoutMinioInstancesRoute
  LayoutOpsRoute: typeof LayoutOpsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRouteWithChildren
  LayoutTagsRoute: typeof LayoutTagsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSamplesSampleIdRoute: typeof LayoutSamplesSampleIdRoute
  LayoutSamplesIndexRoute: typeof LayoutSamplesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBuildRoute: LayoutBuildRoute,
  LayoutDatasetsRoute: LayoutDatasetsRouteWithChildren,
  LayoutImportRoute: LayoutImportRoute,
  LayoutMinioInstancesRoute: LayoutMinioInstancesRoute,
  LayoutOpsRoute: LayoutOpsRoute,
  LayoutSettingsRoute: LayoutSettingsRouteWithChildren,
  LayoutTagsRoute: LayoutTagsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSamplesSampleIdRoute: LayoutSamplesSampleIdRoute,
  LayoutSamplesIndexRoute: LayoutSamplesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
