/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTagsRouteImport } from './routes/_layout/tags'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMinioInstancesRouteImport } from './routes/_layout/minio-instances'
import { Route as LayoutDatasetsRouteImport } from './routes/_layout/datasets'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSamplesIndexRouteImport } from './routes/_layout/samples/index'
import { Route as LayoutSamplesImportRouteImport } from './routes/_layout/samples/import'
import { Route as LayoutSamplesSampleIdRouteImport } from './routes/_layout/samples/$sampleId'
import { Route as LayoutDatasetsDatasetIdReviewRouteImport } from './routes/_layout/datasets/$datasetId/review'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTagsRoute = LayoutTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMinioInstancesRoute = LayoutMinioInstancesRouteImport.update({
  id: '/minio-instances',
  path: '/minio-instances',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDatasetsRoute = LayoutDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSamplesIndexRoute = LayoutSamplesIndexRouteImport.update({
  id: '/samples/',
  path: '/samples/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSamplesImportRoute = LayoutSamplesImportRouteImport.update({
  id: '/samples/import',
  path: '/samples/import',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSamplesSampleIdRoute = LayoutSamplesSampleIdRouteImport.update({
  id: '/samples/$sampleId',
  path: '/samples/$sampleId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDatasetsDatasetIdReviewRoute =
  LayoutDatasetsDatasetIdReviewRouteImport.update({
    id: '/$datasetId/review',
    path: '/$datasetId/review',
    getParentRoute: () => LayoutDatasetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/datasets': typeof LayoutDatasetsRouteWithChildren
  '/minio-instances': typeof LayoutMinioInstancesRoute
  '/settings': typeof LayoutSettingsRoute
  '/tags': typeof LayoutTagsRoute
  '/': typeof LayoutIndexRoute
  '/samples/$sampleId': typeof LayoutSamplesSampleIdRoute
  '/samples/import': typeof LayoutSamplesImportRoute
  '/samples': typeof LayoutSamplesIndexRoute
  '/datasets/$datasetId/review': typeof LayoutDatasetsDatasetIdReviewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/datasets': typeof LayoutDatasetsRouteWithChildren
  '/minio-instances': typeof LayoutMinioInstancesRoute
  '/settings': typeof LayoutSettingsRoute
  '/tags': typeof LayoutTagsRoute
  '/': typeof LayoutIndexRoute
  '/samples/$sampleId': typeof LayoutSamplesSampleIdRoute
  '/samples/import': typeof LayoutSamplesImportRoute
  '/samples': typeof LayoutSamplesIndexRoute
  '/datasets/$datasetId/review': typeof LayoutDatasetsDatasetIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/datasets': typeof LayoutDatasetsRouteWithChildren
  '/_layout/minio-instances': typeof LayoutMinioInstancesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tags': typeof LayoutTagsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/samples/$sampleId': typeof LayoutSamplesSampleIdRoute
  '/_layout/samples/import': typeof LayoutSamplesImportRoute
  '/_layout/samples/': typeof LayoutSamplesIndexRoute
  '/_layout/datasets/$datasetId/review': typeof LayoutDatasetsDatasetIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/datasets'
    | '/minio-instances'
    | '/settings'
    | '/tags'
    | '/'
    | '/samples/$sampleId'
    | '/samples/import'
    | '/samples'
    | '/datasets/$datasetId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/datasets'
    | '/minio-instances'
    | '/settings'
    | '/tags'
    | '/'
    | '/samples/$sampleId'
    | '/samples/import'
    | '/samples'
    | '/datasets/$datasetId/review'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/datasets'
    | '/_layout/minio-instances'
    | '/_layout/settings'
    | '/_layout/tags'
    | '/_layout/'
    | '/_layout/samples/$sampleId'
    | '/_layout/samples/import'
    | '/_layout/samples/'
    | '/_layout/datasets/$datasetId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tags': {
      id: '/_layout/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof LayoutTagsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/minio-instances': {
      id: '/_layout/minio-instances'
      path: '/minio-instances'
      fullPath: '/minio-instances'
      preLoaderRoute: typeof LayoutMinioInstancesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/datasets': {
      id: '/_layout/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof LayoutDatasetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/samples/': {
      id: '/_layout/samples/'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof LayoutSamplesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/samples/import': {
      id: '/_layout/samples/import'
      path: '/samples/import'
      fullPath: '/samples/import'
      preLoaderRoute: typeof LayoutSamplesImportRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/samples/$sampleId': {
      id: '/_layout/samples/$sampleId'
      path: '/samples/$sampleId'
      fullPath: '/samples/$sampleId'
      preLoaderRoute: typeof LayoutSamplesSampleIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/datasets/$datasetId/review': {
      id: '/_layout/datasets/$datasetId/review'
      path: '/$datasetId/review'
      fullPath: '/datasets/$datasetId/review'
      preLoaderRoute: typeof LayoutDatasetsDatasetIdReviewRouteImport
      parentRoute: typeof LayoutDatasetsRoute
    }
  }
}

interface LayoutDatasetsRouteChildren {
  LayoutDatasetsDatasetIdReviewRoute: typeof LayoutDatasetsDatasetIdReviewRoute
}

const LayoutDatasetsRouteChildren: LayoutDatasetsRouteChildren = {
  LayoutDatasetsDatasetIdReviewRoute: LayoutDatasetsDatasetIdReviewRoute,
}

const LayoutDatasetsRouteWithChildren = LayoutDatasetsRoute._addFileChildren(
  LayoutDatasetsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDatasetsRoute: typeof LayoutDatasetsRouteWithChildren
  LayoutMinioInstancesRoute: typeof LayoutMinioInstancesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTagsRoute: typeof LayoutTagsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSamplesSampleIdRoute: typeof LayoutSamplesSampleIdRoute
  LayoutSamplesImportRoute: typeof LayoutSamplesImportRoute
  LayoutSamplesIndexRoute: typeof LayoutSamplesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDatasetsRoute: LayoutDatasetsRouteWithChildren,
  LayoutMinioInstancesRoute: LayoutMinioInstancesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTagsRoute: LayoutTagsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSamplesSampleIdRoute: LayoutSamplesSampleIdRoute,
  LayoutSamplesImportRoute: LayoutSamplesImportRoute,
  LayoutSamplesIndexRoute: LayoutSamplesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
